name: Push container image
on: 
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  

env:
  REGISTRY: quay.io
  IMAGE_NAME: kubevirt/macvtap-cni
  BUILD_PLATFORMS: linux/amd64,linux/arm64,linux/s390x

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        if: github.repository_owner == 'kubevirt'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push latest Macvtap container image
        if: github.repository_owner == 'kubevirt'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest  
          file: ./cmd/Dockerfile

      - name: Build and push tagged Macvtap container image
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{  github.ref_name }}
          file: ./cmd/Dockerfile
